alias: "Alarm Intrusion: unarm when somebody returns"
description: Whenever any members of the family arrive home unset alarm
trigger:
  - platform: state
    entity_id:
      - group.family
    from: not_home
    to: home
condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed
action:
  - service: notify.mobile_app_jtb
    data:
      message: Someone came home - Alarm disabled
      title: Alarm Detect
  - service: alarm_control_panel.alarm_disarm
    metadata: {}
    data: {}
    target:
      entity_id: alarm_control_panel.home_alarm    
mode: single
